import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { SignInButton, useUser, SignOutButton } from '@clerk/nextjs'
import { api } from '@/utils/api'

const Home: NextPage = (props) => {
  const data = api.post.getAll.useQuery()
  const user = useUser()

  console.log({
    post: data.data,
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]'>
        {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
        {user.user ? (
          <div className='text-white'>
            <p>Hi {user.user.username}</p>
            <p>Your email is {user.user.emailAddresses[0]?.emailAddress}</p>
          </div>
        ) : null}
        {data.data && data.data.length > 0 ? (
          <div className='text-white'>
            <h1 className='text-3xl font-bold'>Posts</h1>
            <ul>
              {data.data.map((post) => (
                <li key={post.id}>{post.content}</li>
              ))}
            </ul>
          </div>
        ) : (
          <div className='text-white'>No posts available.</div>
        )}
      </main>
    </>
  )
}

export default Home
