import { LoadingSpinner } from '@/components/Spinner'
import { api } from '@/utils/api'
import { useUser } from '@clerk/nextjs'
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
import { type NextPage } from 'next'
import Head from 'next/head'
dayjs.extend(relativeTime)

const SinglePost: NextPage = (props) => {
  // const id =

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex h-full justify-center '>Post View</main>
    </>
  )
}

export default SinglePost
